import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";
import { apiError, numberValue, text } from "@/lib/http";
import { audit } from "@/lib/audit";
import { notifyInApp, sendEmail } from "@/lib/notifications";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser();const{id}=await params;const ticket=(await query<any>(`SELECT t.*,c.email client_email FROM tickets t JOIN clients c ON c.id=t.client_id WHERE t.id=$1`,[id])).rows[0];if(!ticket)return NextResponse.json({error:'No encontrado'},{status:404});if(user.role==='CLIENT'&&ticket.client_id!==user.clientId)throw new Error('FORBIDDEN');const{rows}=await query(`SELECT m.*,u.email author_email FROM ticket_messages m LEFT JOIN users u ON u.id=m.author_id WHERE ticket_id=$1 AND ($2::boolean=false OR internal=false) ORDER BY created_at`,[id,user.role==='CLIENT']);return NextResponse.json({ticket,messages:rows})}catch(e){return apiError(e)}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser();const{id}=await params;const ticket=(await query<any>(`SELECT t.*,c.email client_email,c.name client_name FROM tickets t JOIN clients c ON c.id=t.client_id WHERE t.id=$1`,[id])).rows[0];if(!ticket)return NextResponse.json({error:'No encontrado'},{status:404});if(user.role==='CLIENT'&&ticket.client_id!==user.clientId)throw new Error('FORBIDDEN');const b=await request.json(),body=text(b.body,10000);if(!body)return NextResponse.json({error:'Mensaje requerido'},{status:400});const internal=user.role!=='CLIENT'&&Boolean(b.internal);const{rows}=await query(`INSERT INTO ticket_messages(ticket_id,author_id,author_name,body,internal) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id,user.id,user.name,body,internal]);if(user.role!=='CLIENT'&&!ticket.first_response_at)await query(`UPDATE tickets SET first_response_at=now(),status=CASE WHEN status='OPEN' THEN 'IN_PROGRESS' ELSE status END WHERE id=$1`,[id]);if(numberValue(b.billableMinutes)>0&&user.role!=='CLIENT')await query(`UPDATE tickets SET billable_minutes=billable_minutes+$2 WHERE id=$1`,[id,numberValue(b.billableMinutes)]);if(!internal){if(user.role==='CLIENT'){const team=await query<{id:string}>(`SELECT id FROM users WHERE active=true AND role IN ('SUPER_ADMIN','ADMIN','SUPPORT')`);await Promise.all(team.rows.map(x=>notifyInApp(x.id,`Respuesta en ${ticket.number}`,body.slice(0,140),ticket.client_id,{ticketId:id})));}else if(ticket.client_email){await sendEmail(ticket.client_email,`${ticket.number} · ${ticket.subject}`,`<p>Hola ${ticket.client_name},</p><p>${body.replace(/\n/g,'<br>')}</p>`,ticket.client_id).catch(()=>null)}}await audit(user.id,'COMMENT','TICKET',id,{messageId:rows[0].id,internal});return NextResponse.json({message:rows[0]},{status:201})}catch(e){return apiError(e)}}
