import crypto from "node:crypto";
import path from "node:path";
import fs from "node:fs/promises";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";
import { audit } from "@/lib/audit";
import { apiError, ok, fail } from "@/lib/http";

const allowed=new Set(['application/pdf','image/png','image/jpeg','image/webp','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
const uploadDir=()=>process.env.UPLOAD_DIR||path.join(process.cwd(),'data','uploads');
async function scopeClient(input:{clientId?:string|null;projectId?:string|null;invoiceId?:string|null;ticketId?:string|null}){
  if(input.clientId)return input.clientId;
  if(input.projectId)return (await query<any>(`SELECT client_id FROM projects WHERE id=$1`,[input.projectId])).rows[0]?.client_id||null;
  if(input.invoiceId)return (await query<any>(`SELECT client_id FROM invoices WHERE id=$1`,[input.invoiceId])).rows[0]?.client_id||null;
  if(input.ticketId)return (await query<any>(`SELECT client_id FROM tickets WHERE id=$1`,[input.ticketId])).rows[0]?.client_id||null;
  return null;
}
export async function GET(request:Request){try{const user=await requireUser();const u=new URL(request.url);const clientId=user.role==='CLIENT'?user.clientId:u.searchParams.get('clientId');const projectId=u.searchParams.get('projectId'),invoiceId=u.searchParams.get('invoiceId'),ticketId=u.searchParams.get('ticketId');const p:unknown[]=[];const clauses:string[]=[];if(clientId){p.push(clientId);clauses.push(`coalesce(d.client_id,pj.client_id,iv.client_id,t.client_id)=$${p.length}`)}if(projectId){p.push(projectId);clauses.push(`d.project_id=$${p.length}`)}if(invoiceId){p.push(invoiceId);clauses.push(`d.invoice_id=$${p.length}`)}if(ticketId){p.push(ticketId);clauses.push(`d.ticket_id=$${p.length}`)}const{rows}=await query(`SELECT d.id,d.client_id,d.project_id,d.invoice_id,d.ticket_id,d.name,d.mime_type,d.size_bytes,d.created_at,u.name created_by_name FROM documents d LEFT JOIN users u ON u.id=d.created_by LEFT JOIN projects pj ON pj.id=d.project_id LEFT JOIN invoices iv ON iv.id=d.invoice_id LEFT JOIN tickets t ON t.id=d.ticket_id ${clauses.length?'WHERE '+clauses.join(' AND '):user.role==='CLIENT'?'WHERE false':''} ORDER BY d.created_at DESC LIMIT 250`,p);return ok({documents:rows})}catch(e){return apiError(e)}}
export async function POST(request:Request){try{const user=await requireUser();const form=await request.formData();const file=form.get('file');if(!(file instanceof File))return fail("VALIDATION", 'Archivo requerido', 400);const max=Math.max(1,Number(process.env.MAX_UPLOAD_MB||15))*1024*1024;if(file.size>max)return fail("PAYLOAD_TOO_LARGE", 'Archivo demasiado grande', 413);if(!allowed.has(file.type))return fail("UNSUPPORTED_MEDIA_TYPE", 'Tipo de archivo no permitido', 415);const clientId=String(form.get('clientId')||'')||null,projectId=String(form.get('projectId')||'')||null,invoiceId=String(form.get('invoiceId')||'')||null,ticketId=String(form.get('ticketId')||'')||null;const scoped=await scopeClient({clientId,projectId,invoiceId,ticketId});if(user.role==='CLIENT'&&scoped!==user.clientId)throw new Error('FORBIDDEN');if(!scoped)return fail("VALIDATION", 'El documento debe pertenecer a un cliente, proyecto, factura o ticket', 400);await fs.mkdir(uploadDir(),{recursive:true});const ext=path.extname(file.name).replace(/[^.a-zA-Z0-9]/g,'').slice(0,12);const key=`${crypto.randomUUID()}${ext}`;await fs.writeFile(path.join(uploadDir(),key),Buffer.from(await file.arrayBuffer()));const display=file.name.replace(/[\r\n]/g,' ').slice(0,240);const{rows}=await query(`INSERT INTO documents(client_id,project_id,invoice_id,ticket_id,name,url,mime_type,size_bytes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,client_id,project_id,invoice_id,ticket_id,name,mime_type,size_bytes,created_at`,[scoped,projectId,invoiceId,ticketId,display,`local:${key}`,file.type,file.size,user.id]);await audit(user.id,'CREATE','DOCUMENT',rows[0].id,rows[0]);return ok({document:rows[0]}, 201)}catch(e){return apiError(e)}}
