import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { query, tx } from "@/lib/db";
import { apiError, text } from "@/lib/http";
import { allocateFiscalNumber, submitEcf } from "@/lib/fiscal";
import { audit } from "@/lib/audit";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser();const{id}=await params;const inv=await query<any>(`SELECT i.*,c.name client_name,c.tax_id,c.email client_email FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.id=$1`,[id]);if(!inv.rows[0])return NextResponse.json({error:'No encontrada'},{status:404});if(user.role==='CLIENT'&&inv.rows[0].client_id!==user.clientId)throw new Error('FORBIDDEN');const items=await query(`SELECT * FROM invoice_items WHERE invoice_id=$1 ORDER BY position`,[id]);const payments=await query(`SELECT * FROM payments WHERE invoice_id=$1 ORDER BY paid_at DESC`,[id]);return NextResponse.json({invoice:inv.rows[0],items:items.rows,payments:payments.rows})}catch(e){return apiError(e)}}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser(['SUPER_ADMIN','ADMIN','FINANCE']);const{id}=await params;const b=await request.json();const action=text(b.action,30);const before=(await query<any>(`SELECT * FROM invoices WHERE id=$1`,[id])).rows[0];if(!before)return NextResponse.json({error:'No encontrada'},{status:404});if(action==='ISSUE'&&before.status==='DRAFT'){const updated=await tx(async c=>{const ncf=await allocateFiscalNumber(c,b.fiscalType||before.fiscal_type);return (await c.query<any>(`UPDATE invoices SET ncf=$2,status='ISSUED',fiscal_type=$3,updated_at=now() WHERE id=$1 RETURNING *`,[id,ncf,b.fiscalType||before.fiscal_type])).rows[0]});try{const ecf=await submitEcf(updated);await query(`UPDATE invoices SET ecf_status=$2,ecf_track_id=$3 WHERE id=$1`,[id,ecf.status,ecf.trackId])}catch{await query(`UPDATE invoices SET ecf_status='FAILED' WHERE id=$1`,[id])}await audit(user.id,'ISSUE','INVOICE',id,updated,before);return NextResponse.json({invoice:updated})}if(action==='VOID'){const{rows}=await query(`UPDATE invoices SET status='VOID',updated_at=now() WHERE id=$1 RETURNING *`,[id]);await audit(user.id,'VOID','INVOICE',id,rows[0],before);return NextResponse.json({invoice:rows[0]})}return NextResponse.json({error:'Acción no soportada'},{status:400})}catch(e){return apiError(e)}}
