"use client";
import { useEffect, useState } from "react";
type Row=Record<string,any>;
const M=(v:any)=>`RD$${Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const D=(v:any)=>v?new Date(v).toLocaleDateString('es-DO'):'—';
async function j(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||d?.error||`HTTP ${r.status}`);return d?.data??d}
export default function Client360({clientId,close}:{clientId:string;close:()=>void}){
 const[data,setData]=useState<any>(),[docs,setDocs]=useState<Row[]>([]),[health,setHealth]=useState<any>(),[error,setError]=useState(''),[contact,setContact]=useState({name:'',email:'',phone:'',title:''}),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([j(`/api/clients/${clientId}`),j(`/api/documents?clientId=${clientId}`)]).then(([a,b])=>{setData(a);setDocs(b.documents||[])}).catch(e=>setError(e.message));
 useEffect(()=>{load();j(`/api/clients/${clientId}/health`).then(setHealth).catch(()=>{})},[clientId]);
 async function addContact(e:React.FormEvent){e.preventDefault();setBusy(true);try{await j('/api/contacts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...contact,clientId})});setContact({name:'',email:'',phone:'',title:''});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const f=new FormData();f.set('file',file);f.set('clientId',clientId);setBusy(true);try{await j('/api/documents',{method:'POST',body:f});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false);e.target.value=''}}
 const c=data?.client;if(!c)return <div className="live-modal-bg"><section className="live-modal"><header><h2>Cliente 360</h2><button onClick={close}>×</button></header><div className="live-empty">{error||'Cargando…'}</div></section></div>;
 return <div className="live-modal-bg"><section className="live-modal client360"><header><div><span className="eyebrow">CLIENT 360</span><h2>{c.name}</h2></div><button onClick={close}>×</button></header>{error&&<div className="live-error">{error}</div>}<div className="client-summary"><div><small>RNC / Cédula</small><b>{c.tax_id||'—'}</b></div><div><small>Health</small><b className={health?`hs-${health.band}`:''}>{health?health.score:c.health_score}<small>/100</small></b></div><div><small>Condición</small><b>{c.payment_terms_days} días</b></div><div><small>Contacto</small><b>{c.email||c.phone||'—'}</b></div></div>
{health&&<section className="client-section health-box"><div className="section-title"><h3>Health score · {health.band==='healthy'?'Saludable':health.band==='attention'?'Atención':'En riesgo'}</h3><span className={`hs-badge hs-${health.band}`}>{health.score}/100</span></div>{(health.factors||[]).length?<ul className="health-factors">{health.factors.map((f:Row,i:number)=><li key={i} className={f.impact<0?'neg':'pos'}><span>{f.impact>0?'+':''}{f.impact}</span><div><b>{f.label}</b><small>{f.detail}</small></div></li>)}</ul>:<small>Sin señales negativas. Relación saludable.</small>}</section>}
<div className="client360-grid"><section><h3>Proyectos</h3>{(data.projects||[]).map((x:Row)=><article className="mini-row" key={x.id}><div><b>{x.name}</b><small>{x.status} · {x.progress}%</small></div><span>{M(x.budget)}</span></article>)}</section><section><h3>Facturas</h3>{(data.invoices||[]).map((x:Row)=><article className="mini-row" key={x.id}><div><b>{x.number}</b><small>{x.status} · {D(x.due_date)}</small></div><span>{M(Number(x.total)-Number(x.paid_amount))}</span></article>)}</section><section><h3>Soporte</h3>{(data.tickets||[]).map((x:Row)=><article className="mini-row" key={x.id}><div><b>{x.number}</b><small>{x.priority} · {x.status}</small></div><span>{x.subject}</span></article>)}</section><section><h3>Activos & renovaciones</h3>{(data.assets||[]).map((x:Row)=><article className="mini-row" key={x.id}><div><b>{x.name}</b><small>{x.type} · {x.provider||'—'}</small></div><span>{D(x.renewal_date)}</span></article>)}</section></div><section className="client-section"><h3>Contactos</h3><div className="contacts-grid">{(data.contacts||[]).map((x:Row)=><article key={x.id}><b>{x.name}</b><small>{x.title||'Contacto'} · {x.email||x.phone||'—'}</small></article>)}</div><form className="inline-form" onSubmit={addContact}><input required placeholder="Nombre" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><input placeholder="Correo" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/><input placeholder="Teléfono" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/><input placeholder="Cargo" value={contact.title} onChange={e=>setContact({...contact,title:e.target.value})}/><button className="secondary-btn" disabled={busy}>Añadir</button></form></section><section className="client-section"><div className="section-title"><h3>Documentos</h3><label className="secondary-btn file-btn">＋ Adjuntar<input type="file" onChange={upload} accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.docx,.xlsx"/></label></div><div className="docs-list">{docs.map(x=><a key={x.id} href={`/api/documents/${x.id}/download`}><div><b>{x.name}</b><small>{x.mime_type} · {Math.ceil(Number(x.size_bytes||0)/1024)} KB</small></div><span>Descargar ↓</span></a>)}{!docs.length&&<small>Sin documentos adjuntos.</small>}</div></section></section></div>
}
